
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/STARTER-team02
owner: ucsb-cs156-f25
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-npm-all-platforms","number":17,"title":"DRAFT: Update npm dependencies for all platforms","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/17"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-storybook-dependency","number":16,"title":"Remove @storybook/addon-essentials","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/16"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/fix-11","number":12,"title":"Create comprehensive GitHub Copilot instructions with validated build times and commands","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/12"}]
