
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/STARTER-team02
owner: ucsb-cs156-f25
repo_name: STARTER-team02
pull_requests: [{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/fix-11","number":12,"title":"[WIP] ✨Set up Copilot instructions","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/12"},{"author":{"is_bot":true,"login":"app/copilot-swe-agent"},"headRefName":"copilot/fix-9","number":10,"title":"[WIP] Change","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/10"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-try-vite-all-at-once","number":8,"title":"DRAFT: Try upgrading to vite all at once","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/8"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-start-vite-migration","number":4,"title":"Vite Migration Spike","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/4"}]
