
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/STARTER-team02
owner: ucsb-cs156-f25
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-update-react-router","number":7,"title":"Update react router","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/7"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-tanstack-table","number":6,"title":"Update node version and TanStack React Table version","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/6"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-all-jsx","number":5,"title":"Rename all JSX files to have a .jsx extension","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/5"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-start-vite-migration","number":4,"title":"Vite Migration Spike","url":"https://github.com/ucsb-cs156-f25/STARTER-team02/pull/4"}]
